### ISSUE TITLE
List out of range

### ISSUE THREAD

**Issue by datatalking** [snehasinghania/CrunchbaseScraper#1]
@snehasinghania I enjoyed reading about your CrunchbaseWrapper and thought to give it a try.

Line 34, 53 and 98 generate a cascading index error.

```
Traceback (most recent call last):
  File "/Users/owner/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.7288.30/PyCharm.app/Contents/bin/owner/sbox/test/PycharmProjects/CrunchbaseWrapper/crunchbase.py", line 98, in <module>
    menu.get(choice, [None, sys.exit])[1]()
  File "/Users/owner/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.7288.30/PyCharm.app/Contents/bin/owner/sbox/test/PycharmProjects/CrunchbaseWrapper/crunchbase.py", line 53, in getInfo
    dict_item = self.extractFeatures(info)
  File "/Users/owner/Library/Application Support/JetBrains/Toolbox/apps/PyCharm-P/ch-0/193.7288.30/PyCharm.app/Contents/bin/owner/sbox/test/PycharmProjects/CrunchbaseWrapper/crunchbase.py", line 34, in extractFeatures
    properties = properties[0]
IndexError: list index out of range
```

I can dig into this deeper but wonder what work arounds this was due to updated in requestss?

**Comment by Thommy299** [comment]
I am having the same problems. Is there a fix already? Thanks!

**Comment by datatalking** [comment]
The problem is there is nothing for it to index, its not finding data. Has the API or scrapper been depricated?
